import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-plus-jakarta',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={plusJakartaSans.className}
    >
      <body>

        <main>
          <div className="min-h-screen bg-[#F4EFEA] text-[#2C2520]">
            <Navbar />
            <main className="max-w-7xl mx-auto p-6">
              {children}
            </main>
            <Footer></Footer>
          </div>
        </main>
      </body>
    </html>
  );
}
